---
- hosts: all
  become: true
  tasks:

    - name: Fix broken packages
      become: yes
      apt:
        autoclean: yes
        autoremove: yes
        dpkg_options: 'force-confold'

    - name: Install Node.js dependencies
      package:
        name:
          - ca-certificates
          - curl
          - gnupg
        state: present

    - name: Create directory for GPG key
      become: yes
      file:
        path: /etc/apt/keyrings
        state: directory

    - name: Import NodeSource GPG key
      become: yes
      shell: |
        NODE_MAJOR=20
        curl https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
        gpg --no-default-keyring --keyring /etc/apt/keyrings/nodesource.gpg --export | apt-key add -

    - name: Create deb repository
      shell: |
        NODE_MAJOR=20
        echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | sudo tee /etc/apt/sources.list.d/nodesource.list


    - name: Import the MongoDB public GPG Key
      shell: wget -qO - https://www.mongodb.org/static/pgp/server-4.4.asc | sudo apt-key add -
      
    - name: Add the MongoDB repository to the list of sources
      shell: echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu $(lsb_release -cs)/mongodb-org/4.4 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.4.list
      




    - name: Update apt cache
      apt:
        update_cache: yes


    - name: Install MongoDB
      apt:
        name: mongodb-org
        state: present
        update_cache: yes


    - name: Install Node.js 
      apt:
        name: nodejs
        state: present

    - name: Install app dependencies
      command: npm install
      args:
        chdir: /home/vagrant/app


    - name: Démarrer l'application 
      command: npm run start
      args:
        chdir: /home/vagrant/app
      become: false 