Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  config.vm.network "forwarded_port", guest: 3000, host: 3000

  config.vm.synced_folder "/home/mathias/Documents/heyy/userapi", "/home/vagrant/app", type: "rsync", rsync__exclude: [".git", "node_modules"]

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provision.yml"
  end
end
