name: Update Changelog

on:
  push:
    branches:
      - main

jobs:
  update-changelog:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
  
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
  
    - name: Install dependencies
      run: npm install
      working-directory: userapi
  
    - name: Configure Git User
      run: |
        git config --global user.name "Nom d'utilisateur"
        git config --global user.email "email@example.com"
  
    - name: Generate Changelog
      run: npx standard-version --release-as minor
      working-directory: userapi
  
    - name: Commit and Push Changelog Updates
      run: |
        git add CHANGELOG.md
        git commit -m "chore: update changelog"
        git push
      working-directory: userapi
  
