name: Update Changelog

on:
  push:
    branches:
      - main

jobs:
  update-changelog:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
  
    - name: Install dependencies
      run: npm install
      working-directory: userapi

    - name: Configure Git User
      run: |
        git config user.name "Nom d'utilisateur"
        git config user.email "email@example.com"

    - name: Generate Changelog
      run: npx standard-version --release-as minor
      working-directory: userapi
      
    - name: Print Changelog
      run: cat CHANGELOG.md
      working-directory: userapi
      
    - name: List changes
      run: git status

    - name: Add Changelog
      run: git add CHANGELOG.md || echo "No changes to commit"
      working-directory: userapi

    - name: Commit and Push Changelog Updates
      run: |
        git diff-index --quiet HEAD || git commit -m "chore: update changelog"
        git push
