name: Mon Workflow GitHub Actions

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Redis
        run: npm install redis

      - name: Install dependencies
        run: npm install
        working-directory : userapi

      - name: Start Redis
        run: redis-server

      - name: Run tests
        run: npm test
        working-directory : userapi/test
        
