name: Tests Redis

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          
      - name: Install dependencies
        run: npm install
        working-directory : userapi

      - name: Install Redis
        run: sudo apt-get install redis-server -y

      - name: Start Redis
        run: redis-server

      - name: Run tests
        run: npm test # Exécutez vos tests Redis ici
